// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw00Nkqywa_BWMXsCoQORgROjcvQWn-8I',
    appId: '1:983918092259:web:b3d5a8f4577fbf46e74ad6',
    messagingSenderId: '983918092259',
    projectId: 'productiv-349e6',
    authDomain: 'productiv-349e6.firebaseapp.com',
    storageBucket: 'productiv-349e6.appspot.com',
    measurementId: 'G-BD73JRWXKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLX8cCZS648tFQUpWi_GdWRObpLNnz8R0',
    appId: '1:983918092259:android:0ad8001a9a884222e74ad6',
    messagingSenderId: '983918092259',
    projectId: 'productiv-349e6',
    storageBucket: 'productiv-349e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNfQepE4vIodCJt47PN3gWqn4vGRZmj4Q',
    appId: '1:983918092259:ios:ce670480dfe7dba2e74ad6',
    messagingSenderId: '983918092259',
    projectId: 'productiv-349e6',
    storageBucket: 'productiv-349e6.appspot.com',
    iosBundleId: 'com.example.produktiv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNfQepE4vIodCJt47PN3gWqn4vGRZmj4Q',
    appId: '1:983918092259:ios:db1b996c0b8ceccfe74ad6',
    messagingSenderId: '983918092259',
    projectId: 'productiv-349e6',
    storageBucket: 'productiv-349e6.appspot.com',
    iosBundleId: 'com.example.produktiv.RunnerTests',
  );
}
